### ISSUE TITLE
Base iteration count on current year.

### ISSUE THREAD

**Issue by ericelliott** [ericelliott/credential#11]
For reference, see:

https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/Crypto/DefaultCrypto.cs#L128

The defaults in the current version of credential are based on recommendations for 2014, so we would use that as the start year.

In order to make this work with credential, we will need to be able to detect expired password hashes so that the user can be prompted to reset credentials. This also ensures that the user is forced to change their password annually.

Note that we probably want to implement this functionality such that it would not be a breaking change. There are already many production apps using the existing version of Credential.

See also: https://github.com/ericelliott/credential/issues/9

**Comment by tjconcept** [comment]
I'd rather not expire my users passwords, but in stead just silently replace hashes with stronger ones 
on log in. I think this has to be handled in user land. Something along the lines of:

1. fetch user from storage
2. verify
3. if hash i considered outdated, save a new hash from cleartext password

**Comment by ericelliott** [comment]
For safety, password should expire periodically, anyway. Not *frequently*, but annually isn't terrible.

**Comment by ericelliott** [comment]
Both those password update options should be out-of-scope for this library, anyway, since they really have nothing to do with password hashing and verification, and everything to do with your UX. Detecting that the password is out of date should be enough to get the ball rolling.

**Comment by tjconcept** [comment]
Yes, but that is the responsibility of the application IMO.

I propose a method such as "expired(hash, threshold) -> bool"
Is there maybe a better word than "expired"? Something stating; this hash could be better.

A threshold compared with a more-than-annual increase would be nice to avoid having all users upgrade at 01.01.2016 00:00:00 on the same server each hour ;-)

**Comment by tjconcept** [comment]
Well, you said it. We were actually more on the same page than I realized.

**Comment by ericelliott** [comment]
:+1: 

How about "untrusted" instead of "expired"?

**Comment by tjconcept** [comment]
Would love to, will try to squeeze it in this weekend.

**Comment by calebboyd** [comment]
It seems that if there isn't an explicit iteration count included with the hash, so there would need to be either a `year` or `created` field added so that the hashes can be calculated and compared. This was my concern in #9.

**Comment by tjconcept** [comment]
I've seen #9, and I think the iteration count should be stored as well. I think this is what scrypt does as well (barrysteyn/node-scrypt).

**Comment by ericelliott** [comment]
I'm willing to ditch the hidden work unit modifier in favor of storing the year in the hash.

**Comment by ericelliott** [comment]
Go ahead with the breaking change. I think that basing iterations on the current year is much more secure than the security by obscurity in the "hidden" iteration count. ;)

**Comment by tjconcept** [comment]
Awesome.
The stored hash should IMO be independent from the implementation such that you can freely update/enhance the implementation without invalidating the whole database.

**Comment by tjconcept** [comment]
I think #14 should be solved first/independently as this seems more like a smaller enhancement to the "determine iterations"-logic.
But I'll happily have a crack at it all in the weekend.

**Comment by ericelliott** [comment]
Sounds like a great plan. Thanks! :+1:
