### ISSUE TITLE
Remove workUnits, credential_key and workKey options in favor of iterations

### ISSUE THREAD

**Issue by calebboyd** [ericelliott/credential#14]
It was always my understanding that the iterations in PBKDF2 were the 'workUnits' and it was algorithms like bcrypt that took an arbitrary workUnit which was then used to compute a time-cost within the algorithm. In that light I'm not sure the options `credential_key` or `workKey` or `workUnits` add any additional security (only obscurity)  besides saving the attacker a few hash comparisons.

**Comment by ericelliott** [comment]
Yep, I'm on board, but let's handle all this in https://github.com/ericelliott/credential/issues/11.

**Comment by ericelliott** [comment]
Solve first, separate from #11.
