### ISSUE TITLE
function for hardening hashes

### ISSUE THREAD

**Issue by denyskoch** [ericelliott/credential#21]
Imagine a function which takes an hash/hash-object and returns an hash/hash-object. The function does nothing more then increase the iteration count and rehash the old one.

This is useful if you want keep your hashes difficult to crack as computer performance is increasing. (e.g with a cronjob)

What do you thing about it?

**Comment by madbence** [comment]
You can't increase the iteration count without the password (afaik):

```js
pkbdf2(pwd, salt, i) !== pkbdf2(pkbdf2(pwd, salt, i / 2), salt, i / 2)
```

**Comment by tjconcept** [comment]
Nice idea, but as @madbence said, I don't think this is possible. I'll have to dig into the implementation of pkbdf2.

**Comment by denyskoch** [comment]
ahh sorry, you are right!

**Comment by brianmhunt** [comment]
You need the original password. [See here](http://en.wikipedia.org/wiki/PBKDF2), where PRF is a keyed HMAC:

```
U1 = PRF(Password, Salt || INT_32_BE(i))
U2 = PRF(Password, U1)
...
Uc = PRF(Password, Uc-1)
```

> Subsequent iterations of PRF use Password as the PRF key and the output of the previous PRF computation as the salt.

It's a neat idea though, @denyskoch . I think it ought to be a consideration for a future algorithm.
