### ISSUE TITLE
Follow the WebCrypto API

### ISSUE THREAD

**Issue by brianmhunt** [ericelliott/credential#22]
It would be good to mimic, insofar as sensible, the [WebCrypto API](http://www.w3.org/TR/WebCryptoAPI/). Consistency across APIs reduces the likelihood of developer misunderstanding and error.

The API is still changing, but it looks like it'll be landing soon.

**Comment by ericelliott** [comment]
Is there anything in that API that is applicable? I don't think they specify a password hashing / verification mechanism, and I certainly didn't see anything that specifies related function signatures. Am I missing something?

**Comment by brianmhunt** [comment]
- PBKDF2 http://www.w3.org/TR/WebCryptoAPI/#pbkdf2
- HMAC http://www.w3.org/TR/WebCryptoAPI/#hmac
- RSASSA-PKCS1-v1_5 http://www.w3.org/TR/WebCryptoAPI/#rsassa-pkcs1
- JWS http://www.w3.org/TR/WebCryptoAPI/#iana-section-jws-jwa

Polyfill: https://github.com/Netflix/NfWebCrypto

Key bit is that the params are the first param, subject (a uint array) the second. For example `cryptoSubtle.digest({ name: "SHA-1" }, text2ua(data))` -- as seen in the polyfill link above.

**Comment by ericelliott** [comment]
That is a low-level API that is not like anything we'd want to present to our users for the purposes of password hashing and verification.

I don't see anything usable here.
