### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by tjconcept** [ericelliott/credential#24]
It has been a while, and even though we have a basic agreement in #16 that you should avoid passwords if possible, this package still seems like a solid implementation, and I would rather have people using it than rolling their own.

I would really like people to have the latest additions (especially e3a7bd4), so I propose we cut a 3.0.0 release.

I have back-ported as much as possible (including e3a7bd4) from the master branch onto a 2.x compatible branch for those who have legacy databases: https://github.com/srcagency/credential/tree/v0.2.x
A neat thing is that passwords will be stored in the "new" format (with iterations - see the legacy test case) meaning that users with existing databases can track this branch for e.g. six months and then do an upgrade to 3.x, then only users who hasn't changed password since will be invalidated.
Of course, this should be done with extreme caution as I haven't actually had the chance to test this on a real database.

Side note:
As an experiment, to gain greater knowledge of my own preferences and code style, I did a complete rewrite of the package (still passing existing tests). If you're interested it is here: https://github.com/srcagency/credential/tree/rewrite and comments are welcome.
See this specific commit's message for a brief summary of changes: https://github.com/srcagency/credential/commit/48b689d08756b1cb66bd8645b7e858952d4e898c.

**Comment by ericelliott** [comment]
I'm not sure I'm following your logic RE: versions.

afaik, e3a7bd4 was a non-breaking change, meaning we don't need a major version bump. We're not even at 1.x, let alone 2.x -- for good reason. I still don't think that we've had adequate expert security review (though we have had a LOT more than most other password libs in npm...)

If we cut a release, it needs to be 1.0.0, and I'm hoping to get a security expert to endorse the lib for the 1.0.0 release. If you want to commit a breaking change after that, the new version will be 2.0.0, not 3.0.0.

Right?

**Comment by ericelliott** [comment]
All this said, I'd be happy to publish the latest master to npm, assuming all the tests still pass and there are no breaking changes. =)

**Comment by tjconcept** [comment]
The version number was a mistake, I meant 0.3.

This is a breaking change, that's why you'd have to increase the version number: https://github.com/ericelliott/credential/commit/47ab3b7874935fcebda6af845871aec9aeca9716
Because we are still on 0.x I guess it is fine to have breaking changes in the minor spot.

The `v0.2.x` branch could be released as 0.2.6.

**Comment by ericelliott** [comment]
Maybe we should just publish the latest *with* the breaking change as v1.0.0 and continue the push for security review towards a v2.0.0 that refuses to work without 2FA? ;)

**Comment by tjconcept** [comment]
Sounds good to me.

But I think we should release a minor upgrade to the current `0.2.5` as well for those that have legacy dbs and want to migrate.

**Comment by ericelliott** [comment]
You want to create a 0.x branch and prep it for a security update?

**Comment by tjconcept** [comment]
As far as I can see none of the new commits are source changes, so I see no value in backporting those to 0.2.x.
My suggestion is therefore:
1. Set up a 0.2.x branch here identical to mine (https://github.com/srcagency/credential/tree/v0.2.x)
2. Bump version to 0.2.6 and release it (upgrade path for all existing users)
3. Release 0.3 from current master

With your "go" I'll happily do 1-2.

**Comment by ericelliott** [comment]
Go! =)

**Comment by tjconcept** [comment]
Done. You should be able to checkout the `v0.2.x` branch and do `npm publish`.

**Comment by ericelliott** [comment]
@tjconcept Do you know if there's any way to delegate publish permissions on npm (as in share them with your team)?

**Comment by tjconcept** [comment]
Sure, just add a collaborator: `npm owner add thomas-jensen credential`

**Comment by ericelliott** [comment]
Done. :sunglasses: 

Precede. =)

**Comment by tjconcept** [comment]
Mission accomplished. Almost two years after the last release, 0.2.6 is up.

**Comment by ericelliott** [comment]
Next stop: 1.0. =)
