### ISSUE TITLE
The Road to 1.0

### ISSUE THREAD

**Issue by snlacks** [ericelliott/credential#26]
Let's get 1.0 released!
- [ ] Update docs
- [ ] Warn about how passwords are obsolete, and users should consider alternatives if possible. Link to other open source library options for 2FA (Google Authenticator, [Twilio SMS verification](https://www.twilio.com/), etc..)
## Original post

I'm using credential in a personal project and _really_ like the focused approach you've taken. Are you still planning on moving ahead to 1.0? Are any contributions are needed from a non-security expert, open source novice?

**Comment by ericelliott** [comment]
As soon as we clear a couple open issues, I'm good to push 1.0.

See https://github.com/ericelliott/credential/issues/27 if you want to pitch in.

**Comment by ericelliott** [comment]
Closing all stale issues and PRs. Please update, ensure all tests pass, and reopen if you really want this in.
