### ISSUE TITLE
Additional Hash Function: scrypt

### ISSUE THREAD

**Issue by chrisspiegl** [ericelliott/credential#3]
It might be a good idea to implement scrypt as an alternative hash function:

https://github.com/barrysteyn/node-scrypt

**Comment by brianmhunt** [comment]
For ease of reference, here is the seminal OpenBSD paper on bcrypt:

http://www.openbsd.org/papers/bcrypt-paper.pdf

**Comment by ericelliott** [comment]
According to [OWASP](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet#Impose_infeasible_verification_on_attacker), PBKDF2 is the only algorithm that qualifies for FIPS certification.

I think that rules the others out for now. I don't want to complicate matters by making people choose if the only available choices are less secure.

**Comment by brianmhunt** [comment]
While PBKDF2 may be the only algorithm qualifying for FIPS certification, I am personally wary of hanging any hat on FIPS as a measure of security, per se.

To quote Ted Unangst's post [The future (or lack thereof) of LibreSSL’s FIPS Object Module](http://opensslrampage.org/post/83555615721):

>  [FIPS is] widely recognized as a worthless checkbox.
> ...
> Note that FIPS mode isn’t just worthless, it’s actively harmful. It creates perverse incentives that lead to a toxic development process where necessary work doesn’t happen and unnecessary work does.

Which is not to say that FIPS compliance is not valuable - just that the value is orthogonal (and some argue detrimental) to security.

One take-away from this might be to make sure the API is extensible, to support bcrypt or scrypt or another algorithm as a plugin, without having to modify the *credential* code.

Just a thought. :)

Cheers

**Comment by ericelliott** [comment]
> Which is not to say that FIPS compliance is not valuable - just that the value is orthogonal (and some argue detrimental) to security.

Noted. I agree with that view, but in this case, the FIPS requirement does reflect the consensus of the security community as far as I'm aware. PBKDF2 is very battle hardened and well researched, and OWASP specifically ranked those recommendations.

> One take-away from this might be to make sure the API is extensible, to support bcrypt or scrypt or another algorithm as a plugin, without having to modify the credential code.

That would be ideal. Is this even possible? They don't all take the same set of parameters. Would we need to expose a lower level API for algorithms? You may notice if you read the source that I did have swapping algorithms in mind when I wrote it. =)

I just haven't taken the time to try to do it, yet. I'm definitely open to a pull request if it doesn't weaken the security. You really have to be careful about opening up new attack vectors when you increase the surface area of the API...

**Comment by brianmhunt** [comment]
Just another [quick link to crypto.SO](http://security.stackexchange.com/questions/4781) for ease-of-reference:

> Bcrypt has the best kind of repute that can be achieved for a cryptographic algorithm: it has been around for quite some time, used quite widely, "attracted attention", and yet remains unbroken to date.

Bcrypt is regarded as being more costly to attack because it is less susceptible to GPU & FPGA optimizations (which speed up SHA-* computations by orders of magnitude, and these are the basis for PBKDF2). There are no equivalent hardware based optimizations for Blowfish, which serves as the basis for bcrypt. Blowfish however, unlike SHA-256, has never been evaluated by NIST.

**Comment by ericelliott** [comment]
:+1: 

I am aware of GPU and FPGA attacks on PBKDF2, however, if memory serves, Blowfish can be accelerated by large memory arrays which can also be built for less than $2k with current hardware. Am I mistaken in that belief?

**Comment by ericelliott** [comment]
A little more info on [hardware acceleration for cryptography](http://wiki.openwrt.org/doc/hardware/cryptographic.hardware.accelerators)

**Comment by brianmhunt** [comment]
Great question. I recalled Blowfish being faster with larger memory space, but I do not know - but would love to see - some comparisons. I have a suspicion that Blowfish is still substantially slower/more expensive than SHA-*, but it would be great to see hard numbers.

**Comment by ericelliott** [comment]
Agreed. =)
