### ISSUE TITLE
Git tag

### ISSUE THREAD

**Issue by hsablonniere** [ericelliott/credential#33]
@tjconcept 

Hey, I wanted to reference a line of code from the `0.2.6` but the tag isn't defined.

**Comment by tjconcept** [comment]
I'm not aware of any `0.2.6` version?

**Comment by tjconcept** [comment]
Sorry.

`0.2.6` was a maintenance release with some back ported fixes. The current master is heading for `1.0` or maybe `0.3.0`.

If you want to reference something in the `0.2` series, you should go to the branch `v0.2.x`. No further development on `v0.2.x` is likely to happen.

**Comment by tjconcept** [comment]
If you have a database of passwords based on an older version, pin to `^0.2.6` until all passwords has expired/been rotated. Then your database is ready for the jump to the next major version.

**Comment by hsablonniere** [comment]
Thanks.

It's just that we use the 0.2.6 from npm and I wanted to reference a line of code in our README (and prove the lib is quite good :p). I wanted to reference the line from 0.2.6 tag.

Don't worry, it's not really important, I used the 713f5f61ad.

**Comment by tjconcept** [comment]
Great :-) I'm keeping my own branch at https://github.com/srcagency/credentials where most of my work land, but I try to port it all here as well.
