### ISSUE TITLE
Result of hash method

### ISSUE THREAD

**Issue by Santinell** [ericelliott/credential#34]
Please add option, which can change result from string into object.
Now I parse it after your stringify. I think is better give to user define type of result

**Comment by tjconcept** [comment]
Why do you want access to the object?
At the moment it is an implementation detail which allows us to change it's format. If we start exposing it, that flexibility is lost.

**Comment by Santinell** [comment]
I want save it in MongoDB like object, not like string.
You think thats wrong or weird?
