### ISSUE TITLE
can't bind hash

### ISSUE THREAD

**Issue by mastilver** [ericelliott/credential#35]
this code is throwing an exception, and doesn't execute the `toHash` function:
```
import credential from 'credential'

credential.hash.bind(this, 'foo', function(err, hashedPassword){
    // never get called
})
```

Checkout this branch for a failing test: https://github.com/mastilver/credential/tree/feature/fix-not-able-to-call-bind

Note: I don't thing hash is the only function affected

**Comment by mastilver** [comment]
I've tried replacing all `this` by `module.exports`, it didn't change anything

**Comment by tjconcept** [comment]
I don't think it makes sense to bind the function to *your* scopes `this` variable? Shouldn't it be the `credential`?

**Comment by mastilver** [comment]
I've just tried:
```
credential.hash.bind(credential, 'foo', function(err, hashedPassword){
    // never get called
})
```

Thank you for the quick answer btw :)

**Comment by tjconcept** [comment]
How do you call this?

This works for me:

```js
var c = require('credential');

var run = c.hash.bind(c, 'test', function( err, h ){
	console.log(h);
});

run();
```

**Comment by mastilver** [comment]
damn... :blush:
I don't use that much bind, That's one problem solved!!

But still when I pass null, it's not working(I can't do otherwise)
I will send you a PR soon :)

**Comment by tjconcept** [comment]
Pass `null` in the context? That's because the `hash` function needs context for configurations.
What do you plan to "fix" in the PR?

**Comment by mastilver** [comment]
yes but instead of using `this` you could use `module.exports`
`this === module.exports` except when you bind it

check my PR for more details

**Comment by tjconcept** [comment]
Ah yes, but we shouldn't have a global configuration in the first place, so I'm afraid you would be adding a feature that would not align with the design goal.
Check out this discussion: https://github.com/ericelliott/credential/issues/25

**Comment by mastilver** [comment]
Cool, Is anyone working on it yet, if not I might pick it up

**Comment by tjconcept** [comment]
Well, I did it the way I prefer in https://github.com/srcagency/credentials but in this repository, no not that I know of.

**Comment by mastilver** [comment]
closing this one for now, thank you for your help!! :+1:
