### ISSUE TITLE
callback, promise or both

### ISSUE THREAD

**Issue by mastilver** [ericelliott/credential#44]
currently the api is using callbacks
What about using Promises instead?

Or we can have both (return Promise if callback is not provided)
I'm sure there is a module that does that, I can't remember witch one...

What do you think?

**Comment by tjconcept** [comment]
:+1: This is exactly what I did with [credentials](https://github.com/srcagency/credentials) using [Bluebird](http://bluebirdjs.com/docs/getting-started.html) (see it's `nodeify` or `asCallback` method).

**Comment by mastilver** [comment]
`nodeify` was the one I was looking for :+1: 
I'm not a big fan of `bluebird` (mainly because it's not following the standard)
I prefer [pinkie](github.com/floatdrop/pinkie)

**Comment by tjconcept** [comment]
Where does it violate the standard?

**Comment by brianmhunt** [comment]
Bluebird is [Promises/A+ v1.1 compliant](https://promisesaplus.com/implementations), and [bluebirdjs.com](http://bluebirdjs.com/docs/why-bluebird.html) notes:

> **Spec compatible** — bluebird can work as a drop-in replacement for native promises for an instant performance boost. It passes the Promises/A+ test suite and is fully spec compliant.

@mastilver, do you just mean bluebird has a bunch added on top of the standard?  (as in pinkie - minimal spec-compliant polyfill)

**Comment by mastilver** [comment]
@brianmhunt yeah, this is what I mean

By using `pinkie`, I'm sure that when I switch to es6, I don't have to rewrite any code.
I will just need to drop `require('pinkie')`

**Comment by brianmhunt** [comment]
@mastilver Got it; yeah, I agree, that's a problem.  IMHO it is imprudent for libraries to use Promise facilities outside ES6.

**Comment by ericelliott** [comment]
There are lots of utilities that can convert a callback API to a promise API, but I would consider a minimal addition that returns a minimal ES6  promise if a callback is not provided.

I'd  prefer a minimal standards-based polyfill for the promise lib.

**Comment by mastilver** [comment]
Cool, I will try to create a PR tomorrow

**Comment by ericelliott** [comment]
=)

**Comment by joepie91** [comment]
The point of Promises/A+ is that implementations can add whatever functionality they consider necessary, as long as base interoperability is accomplished (which it is). There is __no problem whatsoever__ with Bluebird providing additional methods, nor are ES6 Promises a good baseline - they're just *yet another A+ implementation*.
