### ISSUE TITLE
What if an attacker know that I am using this library?

### ISSUE THREAD

**Issue by visualfanatic** [ericelliott/credential#50]
As we know, the `hash` method is returning a JSON string which contains: hash, salt, keyLength, hashMethod, iterations. Now, without knowing how an app using this library is hashing passwords, the attacker will have no way/will be slowed down when trying(?) to crack the passwords, but what if he/she knows that I am using `credential` library (and also its version)?

If you don't mind another question, how would you go about rehashing users passwords with more cycles? https://github.com/ericelliott/credential/issues/23#issuecomment-83959967

**Comment by tjconcept** [comment]
The knowledge of the existence of this package should not change anything unless the attacker is aware of a bug in the software.

Are you talking about a scenario where the database is leaked?

I would rehash the password when the user logs in (you need the cleartext) if the password is older than some threshold I set.

**Comment by visualfanatic** [comment]
Thanks for fast reply! Yes, let's say that the database is leaked, the attacker know how I hash the passwords, doesn't it make it easy for him/her to crack the passwords?

I was thinking about that, but what will be login time difference between for example today and a year later?

**Comment by brianmhunt** [comment]
@visualfanatic The principle upon which you are relying for security is known as [Kerckhoff's principle](https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle), which can be summarized as:

> The security of a cryptosystem should depend solely on the secrecy of the key and the private randomizer. Another way of putting it is that a method of secretly coding and transmitting information should be secure even if everyone knows how it works.

**Comment by visualfanatic** [comment]
@brianmhunt That's why I am asking, I can't see where I could provide my private key, am I missing something?

**Comment by tjconcept** [comment]
The only key is the users password, there are no other "secrets" (private keys) which makes sense because you don't have access to the users password either.

**Comment by visualfanatic** [comment]
Sorry, but I still don't see it, the attacker has my database with user hashes, salts, cycle count etc., knows how I hash users passwords, doesn't it make cracking easier? I know I don't have users password, but I don't see that last security layer, where I could provide one constant secret key, that the attacker doesn't have, and which is used to hash the passwords.

**Comment by brianmhunt** [comment]
> doesn't it make cracking easier?

The key derivation class of functions make reversing a hash ("cracking") a "hard" problem.  By cryptographically "hard", one generally means computationally expensive, and what is computationally expensive requires time and electricity.

The objective of key derivation functions is to make the computational time and expense prohibitive, rendering any attempt at cracking uneconomical.

Not knowing the hash, salt, and cycle count makes the problem more difficult, but the key derivation function provides a baseline computational difficulty.

For practical reasons you generally need to keep the salt, hash, and cycle together.

**Comment by tjconcept** [comment]
What you're referring to is a "pepper", and yes, it *may* give you some additional security in the specific scenario where your database is compromised but your application is not.
If you want to do this, it is as simple as appending your pepper before handing it to the `hash` method.

There are more in-depth answers here: http://security.stackexchange.com/questions/3272/password-hashing-add-salt-pepper-or-is-salt-enough

**Comment by ericelliott** [comment]
Closing all stale issues and PRs. Please update, ensure all tests pass, and reopen if you really want this in.
