### ISSUE TITLE
Why hash() just return string rather than object?

### ISSUE THREAD

**Issue by moslemezzati** [ericelliott/credential#52]
First of all many thanks for your lib, I have a problem to work with your module. when I use hash() it returns a string that has a object for example 
```javascript
pw.hash(body.password, function (err, hash) {
      if (err) {
        console.error(err);
        return;
      }
console.log(type of hash) // string
}
```

but I need `hash.hash`

**Comment by ericelliott** [comment]
It returns a string for database storage and retrieval. The verify function validates using the string. If you need to access the object, you can do so by converting the string to an object with `JSON.parse(string)`.

**Comment by tjconcept** [comment]
You might want to see #46
