### ISSUE TITLE
Does it really needs webpack?

### ISSUE THREAD

**Issue by mastilver** [ericelliott/credential#56]
Webpack seems like an overkill
Why do we need to have a minified version?
Isn't it enough to use babel?

**Comment by ericelliott** [comment]
Can Babel bundle?

**Comment by mastilver** [comment]
why do we need to bundle?
babel will produce a es5 compatible files

**Comment by ericelliott** [comment]
Perhaps we don't. I have not been paying much attention to this repo, honestly. I don't know what we're using Webpack for. If it's overkill, let's kill it.

**Comment by mastilver** [comment]
> If it's overkill, let's kill it.

Alright, let's do it ;)

> I have not been paying much attention to this repo

Fair enough, I guess you are not using it that much (Have you red: [Open Source Stamina](https://medium.com/@kentcdodds/open-source-stamina-dafd063f9932#.cv3gqqn2s) ?)
Would you be ready to give some of us more rights? (I'm mainly thinking about @tjconcept, @brianmhunt and myself)
You gave us the 'Collaborator' role but with the condition not to use our right, which is kind of useless :D

**Comment by ericelliott** [comment]
The condition was that the PR process would be used. Feel free to merge each other's PRs. =)

**Comment by mastilver** [comment]
Cool awesome ;)

Would you be ok using https://github.com/semantic-release/semantic-release so you don't have to care about releases or is that a security issue?

And could you also enable greenkeeper?

I'm asking too much, I will try to shut up now :D

**Comment by ericelliott** [comment]
Closing all stale issues. Please re-open with new PRs if you're still interested.
