### ISSUE TITLE
nice credential hasher

### ISSUE THREAD

**Issue by calebboyd** [ericelliott/credential#9]
Hi Eric, 

Neat module! I only have some suggestions from observation:

A hashing implementation that I had used on a non-node project based it's iterations of PBKDF2 on the current year which seemed convenient.

The relevant c# 
[here](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/Crypto/DefaultCrypto.cs#L69) to [here](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/Crypto/DefaultCrypto.cs#L123), to [here](https://github.com/brockallen/BrockAllen.MembershipReboot/blob/master/src/BrockAllen.MembershipReboot/Crypto/System.Web.Helpers.Crypto.cs#L95)

This implementation also uses the storage technique described [here](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet), and doesn't worry about obfuscation of an explicit iteration count. This could be naive but I don't think an the iteration count being declared on the hash would hurt anything. And it could certainly help when determining if a specific credential needs to be reset so a stronger hash can be created.

Disclaimer: I'm no expert!

-caleb

**Comment by ericelliott** [comment]
Hi Caleb,

I'd be happy to consider a pull request.

**Comment by ericelliott** [comment]
> This could be naive but I don't think an the iteration count being declared on the hash would hurt anything.

I don't see a good reason to take this option away from developers unless it actually adds an attack vector. If users don't want to use it, they can safely use the default value.

**Comment by ericelliott** [comment]
See https://github.com/ericelliott/credential/issues/11

**Comment by ericelliott** [comment]
Also, Thanks! =)
